{
 "title": "Resource Usage per Namespace",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Memory Usage (RSS) Per Namespace",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage (RSS)" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{container!=\"POD\",container=~\".+\"}) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Per Namespace",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none", "label": "CPU Utilization (cores)" }
   ],
   "targets": [
    {
     "expr": "sum(rate (container_cpu_usage_seconds_total{container!=\"POD\",container=~\".+\"}[10m])) by(namespace)",
     "legendFormat": "{{namespace}}"
    }
   ]
  }
 ]
}
{
 "title": "Resource Usage per Pod",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "label": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  {
   "title": "Memory Usage (RSS) Per Pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes", "label": "Memory Usage (RSS)" }
   ],
   "targets": [
    {
     "expr": "container_memory_rss{container!=\"POD\",container=~\".+\",namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}} {{container}}"
    }
   ]
  },
  {
   "title": "CPU Utilization Per Pod",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "CPU Utilization (cores)" }
   ],
   "targets": [
    {
     "expr": "rate (container_cpu_usage_seconds_total{container!=\"POD\",container=~\".+\",namespace=~\"$namespace\"}[10m])",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}