apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.

    scrape_configs:
    - job_name: 'prometheus'
      static_configs:
        - targets: ['localhost:9090']
    - job_name: 'kube-metrics'
      scheme: https
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      file_sd_configs:
        - files:
          - '/var/prometheus/targets.json'
      relabel_configs:
        - source_labels: [__address__]
          regex:  '[^/]+(/.*)'            # capture '/...' part
          target_label: __metrics_path__  # change metrics path
        - source_labels: [__address__]
          regex:  '([^/]+)/.*'            # capture host:port
          target_label: __address__       # change target